### ISSUE TITLE
Source code for converting .nrrd files to .npy files

### ISSUE THREAD

**Issue by monjoybme** [nadeemlab/DoseRTX#17]
Hi,
@sanadeem @gourav3017: Thank you so much for your previous help. I'm exploring whether I can use this approach for training on my dataset. I'm stuck on the data preprocessing step. Do you mind sharing your source code for converting `.nrrd` files to `.npy` files?  I assume the conversion is straightforward, but I am a bit confused about the `hist.npy` and `bins.npy` files because according to step 2.1 of the data preprocessing, the number of input files is 5, and the number of output files is 6. If the code has already been shared in this repository, could you guide me to the file? As per my understanding `data_preprocess.py` converts DICOM data to `.nrrd` format. 

Data preprocessing step 2.1: [https://github.com/nadeemlab/DoseRTX/tree/1537ba9c4b5cbe0eb8c8d1bd5ce189d4251770c3?tab=readme-ov-file#data-pre-processing](url)

Any help will be highly appreciated. Thanks in advance!

**Comment by gourav3017** [comment]
@monjoybme No problem. data_preprocess.py first converts DICOM data to .nrrd and then generates .npy from .nrrd. You can navigate to this part of the code in data_preprocess.py [process_case](https://github.com/nadeemlab/DoseRTX/blob/main/preprocess/data_preprocess.py#L358) where it generates .npy files from .nrrd data for training the model. Let me know if there is any issue. Thanks.

**Comment by monjoybme** [comment]
@gourav3017 Thanks!
