### ISSUE TITLE
Questions about loss

### ISSUE THREAD

**Issue by ChengSongyang** [nadeemlab/DoseRTX#2]
Hi, I notice your novel contribution is the MAE+MomentLoss, but I noticed you have tried MSE+MomentLoss, so have you ever compared the performance difference? which is better? and how about only using MSE? Looking forward to your reply, thank you!

**Comment by sanadeem** [comment]
MAE produces less blurring in the output compared to MSE. Similar observation has been made in previous studies, e.g. [1], where they mention in their discussion section: ``We found that the L2 (MSE) loss function generally leads to blurred images without sharp detail. In general, L2 assumes the probability distribution of the data to be Gaussian and potentially blends multimodal distributions into a unimodal one.''

[1] Fan, Jiawei et al. “Verification of the machine delivery parameters of a treatment plan via deep learning.” Physics in medicine and biology vol. 65,19 195007. 30 Sep. 2020, doi:10.1088/1361-6560/aba165

**Comment by ChengSongyang** [comment]
> MAE produces less blurring in the output compared to MSE. Similar observation has been made in previous studies, e.g. [1], where they mention in their discussion section: ``We found that the L2 (MSE) loss function generally leads to blurred images without sharp detail. In general, L2 assumes the probability distribution of the data to be Gaussian and potentially blends multimodal distributions into a unimodal one.''
> 
> [1] Fan, Jiawei et al. “Verification of the machine delivery parameters of a treatment plan via deep learning.” Physics in medicine and biology vol. 65,19 195007. 30 Sep. 2020, doi:10.1088/1361-6560/aba165

Thanks for your reply! So in this paper, the performance of MSE and MSE+MomentLoss is worse than MAE+MomentLoss? What is the difference in DVH score？

**Comment by sanadeem** [comment]
Yes. I don't recall but the difference wasn't insignificant.
